# Generated by Django 3.1.7 on 2021-03-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_sem_acentos', models.CharField(max_length=255)),
                ('estado_sigla', models.CharField(max_length=2)),
                ('estado', models.CharField(max_length=255)),
                ('estado_sem_acentos', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('tipo', models.CharField(max_length=55)),
                ('status', models.CharField(max_length=55)),
                ('valor_mensal', models.IntegerField()),
                ('proprietario', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario')),
            ],
            options={
                'verbose_name': 'Imovel',
                'verbose_name_plural': 'Imoveis',
            },
        ),
        migrations.CreateModel(
            name='ImovelImagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri_arquivo', models.ImageField(upload_to='imagensImoveis/')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='imovel.imovel')),
            ],
            options={
                'verbose_name': 'Imovel imagem',
                'verbose_name_plural': 'Imovel imagens',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('ponto_de_referencia', models.CharField(blank=True, max_length=55, null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='imovel.cidade')),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imovel.imovel')),
            ],
        ),
    ]
