# Generated by Django 3.1.7 on 2021-03-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovelimagem',
            name='uri_arquivo',
            field=models.FileField(upload_to='C:\\Users\\55849\\Desktop\\Integrador_6_periodo\\files/imagensImoveis/'),
        ),
    ]
