# Generated by Django 3.1.7 on 2021-03-02 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImovelImagens',
            new_name='ImovelImagem',
        ),
    ]
