# Generated by Django 3.1.7 on 2021-03-02 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0002_auto_20210301_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovelimagem',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='imovel.imovel'),
        ),
    ]
