# Generated by Django 3.1.7 on 2021-03-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0002_auto_20210305_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovelimagem',
            name='uri_arquivo',
            field=models.ImageField(upload_to='C:\\Users\\natan\\Desktop\\Integrador_6_periodo\\files/imagensImoveis/'),
        ),
    ]
