# Generated by Django 3.1.7 on 2021-03-07 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('imovel', '0003_auto_20210307_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='proprietario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario'),
        ),
        migrations.AlterField(
            model_name='imovelimagem',
            name='uri_arquivo',
            field=models.ImageField(upload_to='imagensImoveis/'),
        ),
    ]
